"""
The store's public surface, as a Protocol.

Lifted verbatim from the fork's controller, where it existed so the controller and its tests
never needed the real ``GenomeStore`` on disk. It earns its place again here for a different
reason: the pure tier - importers, enrichers, engine - depends only on this shape, so it can be
transplanted and tested with no database and no Home Assistant anywhere near it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Mapping, Sequence

    from .models import ArtistMeta, FailedArtist, GenomeImportResult, GenomeResult, Listen


class GenomeStoreProtocol(Protocol):
    """
    Structural mirror of ``GenomeStore``'s frozen public surface (Part 4).

    Duck-typed on purpose: ``store.py`` is owned by a different work package and may not exist
    on disk yet, so this controller (and its tests) never import the real class directly.
    """

    async def setup(self) -> None: ...
    async def close(self) -> None: ...
    async def add_listens(
        self, listens: Sequence[Listen], *, listener: str, ma_userid: str | None = None
    ) -> GenomeImportResult: ...
    def iter_listens(self, listener: str, *, since: int = 0) -> AsyncIterator[Listen]: ...
    async def count_listens(self, listener: str) -> int: ...
    async def count_eligible_listens(self, listener: str, *, min_seconds_played: int) -> int: ...
    async def get_artist_meta(self, artist_keys: Sequence[str]) -> dict[str, ArtistMeta]: ...
    async def upsert_artist_meta(self, rows: Sequence[ArtistMeta], *, state: str) -> None: ...
    async def pending_artist_keys(self, limit: int = 200) -> list[tuple[str, str]]: ...
    async def get_cached_genome(self, listener: str) -> GenomeResult | None: ...
    async def set_cached_genome(self, listener: str, genome: GenomeResult) -> None: ...
    async def clear(self, listener: str | None = None) -> None: ...
    async def source_counts(self, listener: str) -> dict[str, int]: ...
    async def player_names(self) -> dict[str, str]: ...
    # extensions beyond the frozen Part 4 surface, added during integration (see docs/STATUS.md):
    async def upsert_artist_meta_full(self, rows: Sequence[Any], *, state: str) -> None: ...
    async def update_lb_popularity(self, rows: dict[str, tuple[int, int]]) -> None: ...
    async def pending_popularity_keys(self, limit: int = 200) -> list[tuple[str, str]]: ...
    async def mark_popularity_attempted(self, artist_keys: Sequence[str]) -> None: ...
    async def backfill_done(self) -> bool: ...
    async def mark_backfill_done(self) -> None: ...
    async def lastfm_backfill_done(self) -> bool: ...
    async def mark_lastfm_backfill_done(self) -> None: ...
    async def latest_played_at(self, listener: str, source: str) -> int: ...
    async def lastfm_resume_after(self) -> int: ...
    async def set_lastfm_resume_after(self, timestamp: int) -> None: ...
    async def use_lastfm_account(self, username: str) -> bool: ...
    async def artist_resolution_counts(self) -> dict[str, int]: ...
    async def failed_artist_keys(self, limit: int = 100) -> list[FailedArtist]: ...
    async def retry_failed_artists(self, artist_keys: Sequence[str] | None = None) -> int: ...
    async def all_failed_artist_keys(self) -> frozenset[str]: ...
    async def dismiss_unresolved(self, artist_keys: Sequence[str]) -> None: ...
    async def unresolved_dismissed_keys(self) -> frozenset[str] | None: ...
    async def get_cached_discovery(self, listener: str) -> dict[str, Any] | None: ...
    async def set_cached_discovery(self, listener: str, data: Mapping[str, Any]) -> None: ...
    async def artist_play_counts(self, listener: str) -> dict[str, int]: ...
    async def set_jobs(self, data: dict) -> None: ...
    async def get_jobs(self) -> dict: ...


__all__ = ["GenomeStoreProtocol"]
